export const ROUTE_NAMES = {
	HOME: "/React_HW/",
	SIGN_UP: "/sign-up",
	SIGN_IN: "/sign-in",
	USERS: "/users",
	CLASS_COUNTER: "/class-counter",
	FUNC_COUNTER: "/functional-counter",
	COND_RENDER: "/conditional-rendering",
	COUNTERS_LIST: "/counters-list",
	REDUX_COUNTERS_LIST: "/redux-counters-list",
	FORM: "/form",
	TODO_LIST: "/todo-list",
	RENDER_PROPS: "/render-props",
	DATA_FETCHING: "/data-fetching",
	POKEMONS: "/pokemons",
	POKEMON_INFO: "/pokemons/:pokemonName",
};